# Use root/example as user/password credentials
version: '3.1'

services:
  node:
    image: "node:19.6"
    user: "node"
    working_dir: /server
    environment:
      - NODE_ENV=production
    volumes:
      - /projects/React-coures-app:/server
    expose:
      - "5000"
    ports:
      - 20402:5000
    command: "npm start"

  mongo:
    image: mongo
    restart: always
    volumes:
      - /var/lib/mongodb/data/react_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - main-net

  mongo-express:
    image: mongo-express
    restart: always
    volumes:
      - /var/lib/mongodb/data/react_db:/data/db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
      ME_CONFIG_SITE_BASEURL: /mongoadmin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_OPTIONS_EDITORTHEME: midnight
    networks:
      - main-net
networks:
  main-net:
volumes:
  db_data: